### ISSUE TITLE
Problem running the video demo

### ISSUE THREAD

**Issue by irthomasthomas** [RedisGears/RedisGears#574]
Hi, I used this a couple of years ago but now I guess some things have changed and the demo needs updating? I am getting an error on ubuntu18, I think I have everything installed right but running init.py it says cv2 is not installed. It is not clear anymore where to install requirements for the gears sub interpreter, I tried /var/opt/redislabs/modules/python3 and /var/opt/redislabs/modules/rg but to no avail.

**Comment by MeirShpilraien** [comment]
Assuming you are using the latest docker container, the python interpreter is located under `/var/opt/redislabs/modules/rg/python3_1.0.6/bin/python3`, so basically this should work:
`/var/opt/redislabs/modules/rg/python3_1.0.6/bin/python3 -m pip install opencv-python`

But you can also specify open `opencv-python` as a requirement when you execute the RG.PYEXECUTE command and RedisGears will install it. 

Please notice that when I tried to install cv2 on this container I got this error:
```
(error) ['Traceback (most recent call last):\n', '  File "<string>", line 1, in <module>\n', '  File "/var/opt/redislabs/modules/rg/python3_1.0.6/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>\n    from .cv2 import *\n', 'ImportError: libGL.so.1: cannot open shared object file: No such file or directory\n']
```

I run this directly on the container and it solved it:
```
apt-get update
apt-get install ffmpeg libsm6 libxext6  -y
```

**Comment by irthomasthomas** [comment]
Sorry I should have mentioned I am trying to use the none-docker version as my laptop is a bit slow. Building the redisgears module does not seem to create that same directory.

**Comment by MeirShpilraien** [comment]
So when RedisGears starts it prints to the log file the interpreter location and the virtual environment location (assuming you run with CreateVenv 1), Example:
```
31161:M 30 Jun 2021 18:26:59.596 * <rg> PYENV_DIR: /root/RedisGears/bin/linux-x64-release///python3_99.99.99/
31161:M 30 Jun 2021 18:26:59.596 * <rg> PYENV_HOME_DIR: /root/RedisGears/bin/linux-x64-release///python3_99.99.99//.venv/
31161:M 30 Jun 2021 18:26:59.596 * <rg> PYENV_BIN_DIR: /root/RedisGears/bin/linux-x64-release///python3_99.99.99//.venv//bin
31161:M 30 Jun 2021 18:26:59.596 * <rg> PYENV_ACTIVATE: /root/RedisGears/bin/linux-x64-release///python3_99.99.99//.venv//bin/activate_this.py
31161:M 30 Jun 2021 18:26:59.596 * <rg> PYENV_ACTIVATE_SCRIPT: /root/RedisGears/bin/linux-x64-release///python3_99.99.99//.venv//bin/activate
```

**Comment by MeirShpilraien** [comment]
@irthomasthomas closing (no activity), please reopen if any further help is needed.
