### ISSUE TITLE
redisgears-py install fails

### ISSUE THREAD

**Issue by chrisAtRedisLabs** [RedisGears/RedisGears#584]
Installation of Python client fails in a mint venv with the following error message:
```
pip install git+https://github.com/RedisGears/redisgears-py.git
Collecting git+https://github.com/RedisGears/redisgears-py.git
  Cloning https://github.com/RedisGears/redisgears-py.git to /tmp/pip-req-build-n97s2i53
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-n97s2i53/setup.py'
```
Python is 3.7.3 on a stock Buster installation.

**Comment by chrisAtRedisLabs** [comment]
Let me know if you need more info.

**Comment by chayim** [comment]
@chrisAtRedisLabs You have an out of date version of pip.  Strictly speaking we don't have to uninstall the dist pip this way, but it works. Here's the incantation I used to bring a stock debian buster docker to install:

``` 
docker run -it debian:buster bash
apt update
apt install -y python3 python3-pip git
python3 -m pip install --upgrade pip
pip3 install git+https://github.com/RedisGears/redisgears-py.git
```

In between, validated that the apt install brings us python 3.7.3
