### ISSUE TITLE
failed running gear function

### ISSUE THREAD

**Issue by HenriqueAMiguel** [RedisGears/RedisGears#808]
Hi, I'm trying to add some recipes in RedisGears, and getting this error on pickling or something. Can you help me with this?

Using docker for this on redislabs/redisgears:1.2.5
I already tried with 1.2.4 too

The error:

```
failed running gear function (['Traceback (most recent call last):
  File "<string>", line 368, in <module>
  File "<string>", line 183, in register
gears.error: Error occured when serialized a python callback, callback=fetch_data error=['Traceback (most recent call last):
 File "<string>", line 698, in save_global
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 960, in save_global
    (obj, module_name, name)) from None
_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.decl_api.Base'>: it's not found as sqlalchemy.orm.decl_api.Base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 954, in dumps
  File "<string>", line 267, in dump
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "<string>", line 397, in save_function
  File "<string>", line 596, in save_function_tuple
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 518, in save
    self.save_global(obj)
  File "<string>", line 707, in save_global
  File "<string>", line 530, in save_dynamic_class
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 518, in save
    self.save_global(obj)
  File "<string>", line 707, in save_global
  File "<string>", line 534, in save_dynamic_class
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "<string>", line 402, in save_function
  File "<string>", line 596, in save_function_tuple
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/var/opt/redislabs/modules/rg/python3_1.2.4/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
 TypeError: can't pickle weakref objects
```

I had to minimize the code to not expose my business rule, but it happens even in this minimal document.
The Code:

```
from sqlalchemy import create_engine, Column, String, Integer
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import pickle
import uuid


# region Model

Base = declarative_base()

class Budget(Base):
    __tablename__ = "budget"

    def __init__(self, budgetNumber, budgetSource, budgetStatus, budgetType, insuranceType):
        self.BudgetNumber = budgetNumber
        self.BudgetSource = budgetSource
        self.BudgetStatus = budgetStatus
        self.BudgetType = budgetType
        self.InsuranceType = insuranceType
    
    Id = Column("Id", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)    
    BudgetNumber = Column("BudgetNumber", String)
    BudgetSource = Column("BudgetSource", Integer)
    BudgetStatus = Column("BudgetStatus", Integer)
    BudgetType = Column("BudgetType", Integer)
    InsuranceType = Column("InsuranceType", Integer)

    def __repr__(self):
         return 'Nothing'
    
    def __getstate__(self):
            return {
              'Id': self.Id,
              'BudgetNumber': self.BudgetNumber,
              'BudgetSource': self.BudgetSource,
              'BudgetStatus': self.BudgetStatus,
              'BudgetType': self.BudgetType,
              'InsuranceType': self.InsuranceType
            }

    @classmethod
    def as_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}

# endregion Model

# region Mapper

def map_toPostgres(orcMongo):
    orcamento = Budget(orcMongo["Numero"], 0, 0, 0, 0)
    # orcamento.BudgetNumber = orcMongo["Numero"]
    # orcamento.LegacyId = orcMongo["LegacyId"]
    # orcamento.MongoLegacyId = str(orcMongo["_id"])
    # orcamento.BudgetDate = orcMongo["Data"]
    # orcamento.BudgetSource = 0
    # orcamento.BudgetStatus = 0
    # orcamento.BudgetType = 0
    # if 'DTGanhoPerdido' in orcMongo:
    #     orcamento.EarnedOrLostDateTime = orcMongo["DTGanhoPerdido"] # teste deve ser feito nos campos que podem conter possiveis nulls
    # orcamento.ExpirationDate = orcMongo["DTValidoAte"]
    # orcamento.InsuranceType = 0
    # if 'DataHoraUltimoEnvioMensagemSegurado' in orcMongo:
    #     orcamento.LastMessageSendToInsuredDateTime = orcMongo["DataHoraUltimoEnvioMensagemSegurado"]
    # orcamento.LastMessageVisualizationDateTime = orcMongo["DataHoraUltimaVisualizacaoMensagem"]
    # orcamento.PendingGetQuotationResults = orcMongo["PendentePegarResultadoCalculo"]
    # orcamento.PublicPageShowDetails = orcMongo["ExibicaoDetalhadaPaginaPublica"] if 'DataHoraUltimoEnvioMensagemSegurado' in orcMongo else False

    return orcamento

# endregion Mapper

# region Recipe

def fetch_data(r):
  engine = create_engine("postgresql://postgres:password@dbaddress/customer", echo=True)
  Session = sessionmaker(bind=engine)

  completeKey = r['key']
  key =   completeKey [10:len(  completeKey )]

  if len(chave) > 24:
    session = Session()
    budget = session.query(Budget).filter(Budget.Id==f'{chave}').first()
    session.close()

    serializedBudget = pickle.dumps(budget)
    execute('set', chaveCompleta, serializedBudget)

# endregion Recipe

# Event handling function registration GB = GearsBuilder
GB().foreach(fetch_data).register(eventTypes=['keymiss'], mode="sync")

# Expected to return data missed
```

If I comment the line "budget = session.query(Budget).filter(Budget.Id==f'{key}').first()" then the recipe loads

**Comment by HenriqueAMiguel** [comment]
I've found the problem. Putting the object and the methods inside the function fetch_data RedisGears was able to compreend the object created.
